# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/cheetah/gcam/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gcam

PRODUCT_PACKAGES += \
    GoogleCamera
